### PR TITLE
Feat/client vite setup

### PR DESCRIPTION
**Pull request by yaldram**
- Added `vite` as the build tool for the front-end project, removed `create-react-app`.
- https://github.com/DhiWise/dhiwise-nodejs/pull/35

### CODE REVIEW

**Comment by yaldram** [comment]
@saloni137 I have created this pull request please check.

**Comment by yaldram** [comment]
@saloni137 , for the `eslint` error, I remember when I upgraded my project from `create-react-app` to `vite` I just got rid of `eslint` packages and re-installed them from scratch. This has 2 benefits, first you get rid of version mismatch. Second all the `eslint` packages are now updated to the latest version. Because you are using a monorepo I had doubts, so the eslint I leave it onto you.

**Comment by saloni137** [comment]
@yaldram great. thanks

**Comment by saloni137** [comment]
I will check the linting issues and packages to work with vite

**Pull request merged**
